# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertask',
            name='done_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
