# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_spidertask_done_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
